### ISSUE TITLE
Build is broken in e55b88c9f

### ISSUE THREAD

**Issue by ilya-g** [NLog/NLog#291]
Build is broken because of warning treated as error about missing XML-comments:

```
NLogTraceListener.cs(363,32): error CS1591:  Missing XML comment for publicly visible type or member 'NLog.NLogTraceListener.ProcessLogEventInfo(NLog.LogLevel, string, string, object[], int?, System.Diagnostics.TraceEventType?, System.Guid?)'
```
