### ISSUE TITLE
Migrate to V6: NLogTraceListener not found anymore

### ISSUE THREAD

**Issue by omghb** [NLog/NLog#6038]
When I migrate from NLog v5 to v6 the compiler tells me:

```
error CS0246: The type or namespace name 'NLogTraceListener' could not be found (are you missing a using directive or an assembly reference?)
```

Where is the NLogTraceListener?

**Comment by omghb** [comment]
It took me quite some time to find the information that this class is now in a new NuGet package: `NLog.Targets.Trace`.

Is there somewhere a migration documentation to v6. We have more issues now and I was not able to find good information about the migration. Thanks.

**Comment by snakefoot** [comment]
The [NLog-nuget-package](https://www.nuget.org/packages/NLog#releasenotes-body-tab) has a link to the [NLog v6 - Major Changes](https://nlog-project.org/2025/04/29/nlog-6-0-major-changes.html).

The [NLog release notes](https://github.com/NLog/NLog/releases) for [NLog v6](https://github.com/NLog/NLog/releases/tag/v6.0.0) also have a link to the [NLog v6 - Major Changes](https://nlog-project.org/2025/04/29/nlog-6-0-major-changes.html).

The [NLog Project Homepage](https://nlog-project.org/archives/) also have news-posts about NLog v6 with link to the [NLog v6 - Major Changes](https://nlog-project.org/2025/04/29/nlog-6-0-major-changes.html).

The [NLog Github Homepage](https://github.com/NLog/NLog) also mentions "NLog 6.0 now available" with link to [NLog v6 - Major Changes](https://nlog-project.org/2025/04/29/nlog-6-0-major-changes.html).

The [NLog Wiki Page for TraceListener](https://github.com/NLog/NLog/wiki/NLog-Trace-Listener-for-System-Diagnostics-Trace) also mentions that it Requires nuget-package [NLog.Targets.Trace](https://www.nuget.org/packages/NLog.Targets.Trace) since NLog v6

Happy you were able find the missing piece. If you have found a place that was missing a link to the [NLog v6 - Major Changes](https://nlog-project.org/2025/04/29/nlog-6-0-major-changes.html) then please tell. I have now updated the page to explicit mention `NLogTraceListener`, and not just mention the nuget-package [NLog.Targets.Trace](https://www.nuget.org/packages/NLog.Targets.Trace)

**Comment by omghb** [comment]
👍 Thanks a lot for the links

**Comment by snakefoot** [comment]
Closing issue as resolved, since the [missing piece](https://www.nuget.org/packages/NLog.Targets.Trace) was found.
